baseURL = "https://kenjimanishi.github.io/"
languageCode = "ja-jp"
title = "Nowheresville Wired"
canonifyurls = true
publishDir = "public"
hasCJKLanguage = true
theme = "stip"
[Author]
    name = "Kenji Imanishi"
    bio = "Software Engineer"
[params]
     [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:kenggg1024@gmail.com"
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/kenjimanishi"
